/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MessageLogService } from "../messageLog.service";
import { MessageLogCreateInput } from "./MessageLogCreateInput";
import { MessageLog } from "./MessageLog";
import { MessageLogFindManyArgs } from "./MessageLogFindManyArgs";
import { MessageLogWhereUniqueInput } from "./MessageLogWhereUniqueInput";
import { MessageLogUpdateInput } from "./MessageLogUpdateInput";

export class MessageLogControllerBase {
  constructor(protected readonly service: MessageLogService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MessageLog })
  async createMessageLog(
    @common.Body() data: MessageLogCreateInput
  ): Promise<MessageLog> {
    return await this.service.createMessageLog({
      data: data,
      select: {
        createdAt: true,
        event: true,
        eventDetail: true,
        id: true,
        loggedAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [MessageLog] })
  @ApiNestedQuery(MessageLogFindManyArgs)
  async messageLogs(@common.Req() request: Request): Promise<MessageLog[]> {
    const args = plainToClass(MessageLogFindManyArgs, request.query);
    return this.service.messageLogs({
      ...args,
      select: {
        createdAt: true,
        event: true,
        eventDetail: true,
        id: true,
        loggedAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MessageLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async messageLog(
    @common.Param() params: MessageLogWhereUniqueInput
  ): Promise<MessageLog | null> {
    const result = await this.service.messageLog({
      where: params,
      select: {
        createdAt: true,
        event: true,
        eventDetail: true,
        id: true,
        loggedAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MessageLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateMessageLog(
    @common.Param() params: MessageLogWhereUniqueInput,
    @common.Body() data: MessageLogUpdateInput
  ): Promise<MessageLog | null> {
    try {
      return await this.service.updateMessageLog({
        where: params,
        data: data,
        select: {
          createdAt: true,
          event: true,
          eventDetail: true,
          id: true,
          loggedAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MessageLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMessageLog(
    @common.Param() params: MessageLogWhereUniqueInput
  ): Promise<MessageLog | null> {
    try {
      return await this.service.deleteMessageLog({
        where: params,
        select: {
          createdAt: true,
          event: true,
          eventDetail: true,
          id: true,
          loggedAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
